import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Importa next/head

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Examen Medico",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Examen Médico Personalizado</title> {/* Título personalizado */}
        <link rel="icon" href="/logo.ico" /> {/* Agrega tu favicon aquí */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
