import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Importa Head de next/head

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Examen Medico",
  description: "Generated by Examen Medico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Examen Médico Personalizado</title>
        <link rel="icon" href="/favicon.ico" /> {/* Llama tu favicon */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
